


# Juoksutilastoja

## Kokonaismatka


```{r echo=FALSE, , warning=FALSE, message = FALSE}


library(tidyr); 
library(dplyr); 
library(ggplot2);
library(lubridate);
library(dygraphs)
library(xts)
library(plotly)
theme_set(theme_bw())

juoksut <- read.csv("C:/Users/markaila/Dropbox/tuloksia/juoksut.csv")
#juoksut$pvm <- dmy(juoksut$date)
juoksut$pvm <- as.Date(juoksut$date)


# Plot
figure <- juoksut %>%
  ggplot( aes(x=pvm, y=kokonaisMatka, color=juoksija, group=1,   text = paste('Juoksija:', juoksija, 
                                              '<br>Pvm', pvm,
                                              '<br>Yhteensä', kokonaisMatka ))) + 
  geom_line() +
  geom_point()  + theme(legend.position="bottom") + ylab("Kokonaismatka") + xlab("Päivämäärä") 


# Turn it interactive with ggplotly
p <- ggplotly(figure, tooltip = "text") %>%
  layout(legend = list(
      orientation = "h"
    )
    
    )
  

p


```

## Juoksulenkkien pituudet

```{r echo=FALSE, , warning=FALSE, message = FALSE}


library(tidyr); 
library(dplyr); 
library(ggplot2);
library(lubridate);
library(dygraphs)
library(xts)
library(plotly)

theme_set(theme_bw())


juoksut <- read.csv("C:/Users/markaila/Dropbox/tuloksia/juoksut.csv")
#juoksut$pvm <- dmy(juoksut$date)
juoksut$pvm <- as.Date(juoksut$date)

figure <- juoksut %>%
  ggplot( aes(x=pvm, y=matka , color=juoksija, text = paste('Juoksija:', juoksija, 
                                              '<br>Pvm', pvm,
                                              '<br>Lenkin pituus', matka ))) + 
  geom_point(size=3) + 
  geom_segment(aes(x=pvm, 
                   xend=pvm, 
                   y=0, 
                   yend=matka))



# Turn it interactive with ggplotly
p <- ggplotly(figure, tooltip = "text") %>%
  layout(legend = list(
      orientation = "h"
    )
    
    )

p
  
```

## Lenkkien pituuksien Jakaumat

```{r echo=FALSE, , warning=FALSE, message = FALSE}


library(tidyr); 
library(dplyr); 
library(ggplot2);
library(lubridate);
library(dygraphs)
library(xts)
library(plotly)

theme_set(theme_bw())


juoksut <- read.csv("C:/Users/markaila/Dropbox/tuloksia/juoksut.csv")
#juoksut$pvm <- dmy(juoksut$date)
juoksut$pvm <- as.Date(juoksut$date)

figure <- juoksut %>%
 ggplot( aes(x=matka)) + 
  geom_density(color="darkblue", fill="lightblue") + 
  facet_grid(juoksija ~ .)




# Turn it interactive with ggplotly
p <- ggplotly(figure)
  
p


```



